### ISSUE TITLE
`make test` fails on cloning github.com:cognitect-labs/test-runner

### ISSUE THREAD

**Issue by px0** [coast-framework/coast#18]
`make test` with a fresh copy of coast as of yesterday fails authentication on macos/jvm8

Also, is there a way to pinpoint the version I'm using? If not, you may want to add that to make error reporting easier

```
/tmp/myapp❯ make test                                                                                 
clj -A\:test
Cloning: git@github.com:cognitect-labs/test-runner
Error building classpath. git@github.com:cognitect-labs/test-runner: Auth fail
org.eclipse.jgit.api.errors.TransportException: git@github.com:cognitect-labs/test-runner: Auth fail
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:248)
	at org.eclipse.jgit.api.CloneCommand.fetch(CloneCommand.java:306)
	at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:200)
	at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:89)
	at clojure.tools.gitlibs.impl$call_with_auth.invokeStatic(impl.clj:49)
	at clojure.tools.gitlibs.impl$call_with_auth.invoke(impl.clj:41)
	at clojure.tools.gitlibs.impl$git_clone_bare.invokeStatic(impl.clj:71)
	at clojure.tools.gitlibs.impl$git_clone_bare.invoke(impl.clj:68)
	at clojure.tools.gitlibs.impl$ensure_git_dir.invokeStatic(impl.clj:110)
	at clojure.tools.gitlibs.impl$ensure_git_dir.invoke(impl.clj:100)
	at clojure.tools.gitlibs$resolve.invokeStatic(gitlibs.clj:33)
	at clojure.tools.gitlibs$resolve.invoke(gitlibs.clj:29)
	at clojure.tools.gitlibs$procure.invokeStatic(gitlibs.clj:47)
	at clojure.tools.gitlibs$procure.invoke(gitlibs.clj:41)
	at clojure.tools.deps.alpha.extensions.git$eval894$fn__896.invoke(git.clj:41)
	at clojure.lang.MultiFn.invoke(MultiFn.java:238)
	at clojure.tools.deps.alpha$expand_deps.invokeStatic(alpha.clj:177)
	at clojure.tools.deps.alpha$expand_deps.invoke(alpha.clj:161)
	at clojure.tools.deps.alpha$resolve_deps.invokeStatic(alpha.clj:224)
	at clojure.tools.deps.alpha$resolve_deps.invoke(alpha.clj:206)
	at clojure.tools.deps.alpha.script.make_classpath$create_classpath.invokeStatic(make_classpath.clj:59)
	at clojure.tools.deps.alpha.script.make_classpath$create_classpath.invoke(make_classpath.clj:52)
	at clojure.tools.deps.alpha.script.make_classpath$run.invokeStatic(make_classpath.clj:70)
	at clojure.tools.deps.alpha.script.make_classpath$run.invoke(make_classpath.clj:64)
	at clojure.tools.deps.alpha.script.make_classpath$_main.invokeStatic(make_classpath.clj:109)
	at clojure.tools.deps.alpha.script.make_classpath$_main.doInvoke(make_classpath.clj:84)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:702)
	at clojure.core$apply.invokeStatic(core.clj:657)
	at clojure.main$main_opt.invokeStatic(main.clj:317)
	at clojure.main$main_opt.invoke(main.clj:313)
	at clojure.main$main.invokeStatic(main.clj:424)
	at clojure.main$main.doInvoke(main.clj:387)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:702)
	at clojure.main.main(main.java:37)
Caused by: org.eclipse.jgit.errors.TransportException: git@github.com:cognitect-labs/test-runner: Auth fail
	at org.eclipse.jgit.transport.JschConfigSessionFactory.getSession(JschConfigSessionFactory.java:172)
	at clojure.tools.gitlibs.impl.proxy$org.eclipse.jgit.transport.JschConfigSessionFactory$ff19274a.getSession(Unknown Source)
	at org.eclipse.jgit.transport.SshTransport.getSession(SshTransport.java:140)
	at org.eclipse.jgit.transport.TransportGitSsh$SshFetchConnection.<init>(TransportGitSsh.java:280)
	at org.eclipse.jgit.transport.TransportGitSsh.openFetch(TransportGitSsh.java:170)
	at org.eclipse.jgit.transport.FetchProcess.executeImp(FetchProcess.java:137)
	at org.eclipse.jgit.transport.FetchProcess.execute(FetchProcess.java:123)
	at org.eclipse.jgit.transport.Transport.fetch(Transport.java:1269)
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:237)
	... 35 more
Caused by: com.jcraft.jsch.JSchException: Auth fail
	at com.jcraft.jsch.Session.connect(Session.java:519)
	at org.eclipse.jgit.transport.JschConfigSessionFactory.getSession(JschConfigSessionFactory.java:126)
	... 43 more
make: *** [test] Error 1
```

**Comment by swlkr** [comment]
Interesting... let me fix this too

**Comment by swlkr** [comment]
Oh and yeah I did switch back to versions not just git SHAs, I’ve been tagging releases here  and putting them on clojars.

**Comment by swlkr** [comment]
Hm, I just tried this with my updated version of the template, I deleted the `.cpcache` folder and the `~/.gitlibs/libs/com.cognitect` folder and it appeared to work

```sh
➜ ~/Projects/template-test make test
clj -A\:test
Checking out: git@github.com:cognitect-labs/test-runner at 5f2b5c2efb444df76fb5252102b33f542ebf7f58

Running tests in #{"test"}

Testing server-test
GET /not-found  404 text/html; charset=utf-8 86ms
GET / home.index/view 200 text/html; charset=utf-8 4ms

Ran 2 tests containing 2 assertions.
0 failures, 0 errors.
```

**Comment by px0** [comment]
This seems to have to do with how I have my github credentials (per ssh key) set up on my system.
FWIW if I'm using the alternative coordinates it works because it's just downloading it using plain anonymous HTTPS!

```
 {com.cognitect/test-runner {:git/url "https://github.com/cognitect-labs/test-runner.git"
                               :sha "5f2b5c2efb444df76fb5252102b33f542ebf7f58"}}```

**Comment by px0** [comment]
Sorry, wrong button 😬

**Comment by swlkr** [comment]
Yeah I’ll switch it to https, I’m not attached to git
