### ISSUE TITLE
Cambada fails with NullPointerException

### ISSUE THREAD

**Issue by mgerlach-klick** [coast-framework/coast#35]
`make uberjar` results in
```sh
#...
Skipping paths: resources
Warning: skipped duplicate file: assets.edn
Warning: skipped duplicate file: migrations/20180926130454_initial_schema.edn
Warning: skipped duplicate file: migrations/20180927091220_full_image.edn
Warning: skipped duplicate file: public/css/app.css
Warning: skipped duplicate file: public/js/app.js
Warning: skipped duplicate file: schema.edn
Exception in thread "main" java.lang.NullPointerException
	at clojure.tools.deps.alpha.extensions.maven$eval3355$fn__3358.invoke(maven.clj:40)
	at clojure.lang.MultiFn.invoke(MultiFn.java:238)
	at clojure.tools.deps.alpha$canonicalize_deps$fn__3686.invoke(alpha.clj:61)
	at clojure.lang.PersistentVector.reduce(PersistentVector.java:341)
	at clojure.core$reduce.invokeStatic(core.clj:6747)
	at clojure.core$reduce.invoke(core.clj:6730)
	at clojure.tools.deps.alpha$canonicalize_deps.invokeStatic(alpha.clj:60)
	at clojure.tools.deps.alpha$canonicalize_deps.invoke(alpha.clj:58)
	at clojure.tools.deps.alpha$expand_deps.invokeStatic(alpha.clj:170)
	at clojure.tools.deps.alpha$expand_deps.invoke(alpha.clj:152)
	at clojure.tools.deps.alpha$resolve_deps.invokeStatic(alpha.clj:215)
	at clojure.tools.deps.alpha$resolve_deps.invoke(alpha.clj:197)
	at cambada.uberjar$get_dep_jars.invokeStatic(uberjar.clj:109)
	at cambada.uberjar$get_dep_jars.invoke(uberjar.clj:107)
	at cambada.uberjar$apply_BANG_.invokeStatic(uberjar.clj:132)
	at cambada.uberjar$apply_BANG_.invoke(uberjar.clj:129)
	at cambada.cli$runner.invokeStatic(cli.clj:120)
	at cambada.cli$runner.invoke(cli.clj:115)
	at cambada.uberjar$_main.invokeStatic(uberjar.clj:142)
	at cambada.uberjar$_main.doInvoke(uberjar.clj:140)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:702)
	at clojure.core$apply.invokeStatic(core.clj:657)
	at clojure.main$main_opt.invokeStatic(main.clj:317)
	at clojure.main$main_opt.invoke(main.clj:313)
	at clojure.main$main.invokeStatic(main.clj:424)
	at clojure.main$main.doInvoke(main.clj:387)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:702)
	at clojure.main.main(main.java:37)
make: *** [uberjar] Error 1
```

On the other hand, this works for me (deps.ed)):
```clj
  :uberjar2
  {:extra-deps
   {pack/pack.alpha {:git/url "https://github.com/juxt/pack.alpha.git" :sha "dccf2134bcf03726a9465d2b9997c42e5cd91bff"}}
   :main-opts ["-m" "mach.pack.alpha.capsule" "-d" "deps.edn" "-e" "target" "-m" "server" "dist/myapp.jar"]}


```

**Comment by mgerlach-klick** [comment]
```clj
  :uberjar3
  {:extra-deps
   {pack/pack.alpha {:git/url "https://github.com/juxt/pack.alpha.git" :sha "dccf2134bcf03726a9465d2b9997c42e5cd91bff"}}
   :main-opts ["-m" "mach.pack.alpha.one-jar"
               "-d" "deps.edn"
               "dist/myapp.jar"]}
```
... and this one here even produces uberjar that run on windows. The other ones work fine on MacOS but fail with a message about 'Failed to find Premain-Class manifest attribute' on Windows.

**Comment by swlkr** [comment]
I switched from pack.alpha to cut down on dependencies that weren't already included with coast, cambada's deps are all org.clojure deps that are already installed usually. This may not matter though since it's in an alias...

I did notice that cambada threw exceptions when I tried to resolve git deps, but it appeared to work (at least on macOS) for clojars deps, which was an ok trade off at the time, but if it's not working for other reasons, then it might be time to switch back
