### ISSUE TITLE
trying to run make commands

### ISSUE THREAD

**Issue by natetech333** [coast-framework/coast#55]
nathans-MacBook:mycoastapp nathansire$ make test
COAST_ENV=test clj -A\:test
Exception in thread "main" java.io.FileNotFoundException: -A:test (No such file or directory)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:195)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at java.io.FileInputStream.<init>(FileInputStream.java:93)
        at clojure.lang.Compiler.loadFile(Compiler.java:7449)
        at clojure.main$load_script.invokeStatic(main.clj:278)
        at clojure.main$script_opt.invokeStatic(main.clj:338)
        at clojure.main$script_opt.invoke(main.clj:333)
        at clojure.main$main.invokeStatic(main.clj:424)
        at clojure.main$main.doInvoke(main.clj:387)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.lang.Var.applyTo(Var.java:702)
        at clojure.main.main(main.java:37)
make: *** [test] Error 1
nathans-MacBook:mycoastapp nathansire$ clj -A\:test
Exception in thread "main" java.io.FileNotFoundException: -A:test (No such file or directory)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:195)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at java.io.FileInputStream.<init>(FileInputStream.java:93)
        at clojure.lang.Compiler.loadFile(Compiler.java:7449)
        at clojure.main$load_script.invokeStatic(main.clj:278)
        at clojure.main$script_opt.invokeStatic(main.clj:338)
        at clojure.main$script_opt.invoke(main.clj:333)
        at clojure.main$main.invokeStatic(main.clj:424)
        at clojure.main$main.doInvoke(main.clj:387)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.lang.Var.applyTo(Var.java:702)
        at clojure.main.main(main.java:37)
nathans-MacBook:mycoastapp nathansire$ clj
Clojure 1.9.0
user=> -A\:test
CompilerException java.lang.RuntimeException: Unable to resolve symbol: -A in this context, compiling:(NO_SOURCE_PATH:0:0) 
RuntimeException Unsupported character: \:test  clojure.lang.Util.runtimeException (Util.java:221)
user=>

**Comment by swlkr** [comment]
What does your `deps.edn` file look like in that `mycoastapp` directory?

**Comment by natetech333** [comment]
I am using the default files. I will upload to github and share... allow me
1 hour. I am excited.

**Comment by natetech333** [comment]
I see the syntax in the makefile for numerous commans. The coast commands are found e.g. ```coast gen code todo```

But non of the makefile commands are found with the -A prefix

What does the -A prefix stand for?

**Comment by natetech333** [comment]
Created a new coast project in directory mycoastapp2
nathans-MacBook:mycoastapp2 nathansire$ make db/create
clj -m coast.db create
Downloading: coast-framework/coast.theta/1.0.0/coast.theta-1.0.0.pom from https://repo.clojars.org/
Downloading: org/xerial/sqlite-jdbc/3.25.2/sqlite-jdbc-3.25.2.pom from https://repo1.maven.org/maven2/
Downloading: com/zaxxer/HikariCP/2.7.8/HikariCP-2.7.8.pom from https://repo1.maven.org/maven2/
Downloading: hiccup/hiccup/2.0.0-alpha2/hiccup-2.0.0-alpha2.pom from https://repo.clojars.org/
Downloading: org/slf4j/slf4j-nop/1.7.25/slf4j-nop-1.7.25.pom from https://repo1.maven.org/maven2/
Downloading: org/clojure/java.jdbc/0.7.8/java.jdbc-0.7.8.pom from https://repo1.maven.org/maven2/
Downloading: com/zaxxer/HikariCP/2.7.8/HikariCP-2.7.8.jar from https://repo1.maven.org/maven2/
Downloading: coast-framework/coast.theta/1.0.0/coast.theta-1.0.0.jar from https://repo.clojars.org/
Downloading: hiccup/hiccup/2.0.0-alpha2/hiccup-2.0.0-alpha2.jar from https://repo.clojars.org/
Downloading: org/slf4j/slf4j-nop/1.7.25/slf4j-nop-1.7.25.jar from https://repo1.maven.org/maven2/
Downloading: org/clojure/java.jdbc/0.7.8/java.jdbc-0.7.8.jar from https://repo1.maven.org/maven2/
Downloading: org/xerial/sqlite-jdbc/3.25.2/sqlite-jdbc-3.25.2.jar from https://repo1.maven.org/maven2/
Downloading: org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25.jar from https://repo1.maven.org/maven2/
mycoastapp2_dev.sqlite3 created successfully
nathans-MacBook:mycoastapp2 nathansire$

**Comment by natetech333** [comment]
upgrading to Clojure 1.10.0 has fixed it. I will do a pull request just to update the README

**Comment by natetech333** [comment]
I am too new to your project. But I can say from my experience from Rails. It would be great if we can make all commands use ```coast xxxx```. Because Rails had commands under ```rake``` and ```rails```. And they eventually combined all commands under ```rails```. I love the name too. Coast on Clojure.
